INSERT INTO USUARIO(USUARIO_CODIGO, LOGIN , SENHA , TIPO_USUARIO)
VALUES (99999,'muricysampaio','ijurisenha',1);

INSERT INTO ESTADO(ESTADO_CODIGO,NOM_ESTADO,SIG_ESTADO)
VALUES(7000,'Bahia','BA');

INSERT INTO DIRETORIO VALUES(1,'Sistema IJURI - Muricy & Sampaio',null,'/00')
ALTER SEQUENCE SEQ_DIRETORIO START 2;