SELECT P.STR_NUMERO_PROCESSO,A.ACORDO_CODIGO,
       PA.DT_REPASSE,PA.VL_REPASSE,
       PAG.DT_PAGAMENTO,PAG.VL_PAGO,
       PAG.VL_VENCIMENTO,PAG.DT_VENCIMENTO,
       PA.VL_HONORARIO, PA.NUM_PARCELA||'/'||A.QTD_PARCELAS AS NUM_PARCELA_FMT,
       VW_REU.NOME,VW_REU.BLOCO,VW_REU.APTO,
       (SELECT VW_AUTOR.NOME
        FROM VW_AUTOR
             INNER JOIN PROCESSO  
                   ON (PROCESSO.PROCESSO_CODIGO = VW_AUTOR.PROCESSO_CODIGO)
        WHERE PROCESSO.PROCESSO_CODIGO = P.PROCESSO_CODIGO
        ) AS NOME_AUTOR
FROM ACORDO A
     INNER JOIN PARCELA_ACORDO PA 
     ON (A.ACORDO_CODIGO = PA.ACORDO_CODIGO)	
     INNER JOIN PAGAMENTO PAG
     ON (PAG.PAGAMENTO_CODIGO = PA.PARCELA_ACORDO_CODIGO)
     INNER JOIN PROCESSO P 
     ON (A.PROCESSO_CODIGO = P.PROCESSO_CODIGO)
     INNER JOIN VW_REU
     ON (P.PROCESSO_CODIGO = VW_REU.PROCESSO_CODIGO)	
WHERE       //AND (PARTE_DEVEDOR.TIPO_PARTE = 1 AND PESSOA_DEVEDOR.PESSOA_CODIGO = 1)
      (PA.DT_REPASSE > DATE '2001-02-16') /*AND
      VW_REU.PESSOA_CODIGO = 3 */







