--alter table pessoa add column CEP varchar(20) null;
ALTER TABLE PESSOA ADD COLUMN TELEFONE VARCHAR(25);
ALTER TABLE PESSOA ALTER COLUMN OBSERVACAO DROP NOT NULL;


DROP TABLE TIPO_ORGAO_JUDICIARIO CASCADE;
ALTER TABLE ORGAO_JUDICIARIO DROP COLUMN tipo_orgao_judiciario_codigo;
ALTER TABLE CLASSE_PROCESSO DROP COLUMN juizo_codigo;

-- FERNANDO 14/05/2005
ALTER TABLE TIPO_ANDAMENTO DROP COLUMN JUIZO_CODIGO;

DROP TABLE tipo_andamento_juizo;

CREATE TABLE TIPO_ANDAMENTO_JUIZO (
  TIPO_ANDAMENTO_CODIGO INTEGER NOT NULL,
  JUIZO_CODIGO INTEGER NULL,
  PRIMARY KEY(TIPO_ANDAMENTO_CODIGO),
  FOREIGN KEY(JUIZO_CODIGO)
    REFERENCES JUIZO(JUIZO_CODIGO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(TIPO_ANDAMENTO_CODIGO)
    REFERENCES TIPO_ANDAMENTO(TIPO_ANDAMENTO_CODIGO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);
-- FERNANDO 14/05/2005

-- AMADEU 15/05/2005
ALTER TABLE processo DROP COLUMN STR_turno; 
ALTER TABLE processo ADD COLUMN turno_codigo int4;
-- AMADEU 15/05/2005

-- FERNANDO 17/05/2005
DROP TABLE tipo_andamento_juizo;
	
CREATE TABLE TIPO_ANDAMENTO_JUIZO (
  TIPO_ANDAMENTO_CODIGO INTEGER NOT NULL,
  JUIZO_CODIGO INTEGER NULL,
  PRIMARY KEY(TIPO_ANDAMENTO_CODIGO, JUIZO_CODIGO),
  FOREIGN KEY(JUIZO_CODIGO)
    REFERENCES JUIZO(JUIZO_CODIGO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(TIPO_ANDAMENTO_CODIGO)
    REFERENCES TIPO_ANDAMENTO(TIPO_ANDAMENTO_CODIGO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);
-- FERNANDO 17/05/2005

-- AMADEU 23/05/2005
ALTER TABLE processo DROP COLUMN dt_autucao;
ALTER TABLE processo ADD COLUMN dt_autuacao date;
-- AMADEU 23/05/2005

-- AMADEU 01/06/2005
ALTER TABLE ANDAMENTO DROP COLUMN STS_ANDAMENTO;
ALTER TABLE ANDAMENTO ADD COLUMN  STS_INTERNO INT4;
-- AMADEU 01/06/2005

-- AMADEU 06/06/2005
ALTER TABLE andamento ADD COLUMN dth_prazo timestamp;
ALTER TABLE andamento drop column dt_prazo;
-- AMADEU 06/06/2005

-- AMADEU 08/06/2005
ALTER TABLE pessoa DROP COLUMN str_telefone;
ALTER TABLE pessoa ADD COLUMN str_telefone text;
-- AMADEU 08/06/2005

-- AMADEU 13/08/2005
DROP SEQUENCE seq_parcela_acordo;
ALTER TABLE PARCELA_ACORDO DROP COLUMN vl_parcela;
ALTER TABLE PARCELA_ACORDO DROP COLUMN dt_vencimento;

ALTER TABLE PAGAMENTO ADD COLUMN DT_VENCIMENTO DATE;
ALTER TABLE PAGAMENTO ALTER COLUMN DT_VENCIMENTO SET NOT NULL;

ALTER TABLE PAGAMENTO RENAME COLUMN VL_PAGAMENTO TO VL_VENCIMENTO;
-- AMADEU 13/08/2005

-- AMADEU 26/09/2005
ALTER TABLE PAGAMENTO DROP COLUMN FORMA_PAGAMENTO_CODIGO;
ALTER TABLE PAGAMENTO ADD FORMA_PAGAMENTO_CODIGO INTEGER NULL; 
ALTER TABLE PAGAMENTO DROP COLUMN VL_PAGO;
ALTER TABLE PAGAMENTO ADD COLUMN VL_PAGO FLOAT NULL;
ALTER TABLE PAGAMENTO DROP COLUMN DT_PAGAMENTO;
ALTER TABLE PAGAMENTO ADD COLUMN DT_PAGAMENTO DATE NULL;
-- AMADEU 26/09/2005

-- AMADEU 31/09/2005
--ALTER TABLE PARCELA_ACORDO DROP CONSTRAINT parcela_acordo_pagamento_codigo_fkey; 
ALTER TABLE PARCELA_ACORDO ADD CONSTRAINT parcela_acordo_pagamento_codigo_fkey FOREIGN KEY (pagamento_codigo) 
REFERENCES pagamento (pagamento_codigo) ON UPDATE NO ACTION ON DELETE CASCADE;
-- AMADEU 31/09/2005

-- AMADEU 08/09/2005
ALTER TABLE PESSOA DROP COLUMN BLOCO;
ALTER TABLE PESSOA ADD COLUMN BLOCO character varying(25);
-- AMADEU 08/09/2005

-- AMADEU 10/09/2005
ALTER TABLE banco DROP COLUMN banco_codigo CASCADE;	
ALTER TABLE banco ADD PRIMARY KEY (NUM_BANCO);
ALTER TABLE CHEQUE RENAME COLUMN BANCO_CODIGO TO NUM_BANCO;
ALTER TABLE CHEQUE ADD CONSTRAINT CHEQUE_FKEY FOREIGN KEY (NUM_BANCO) 
REFERENCES BANCO (NUM_BANCO) ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE CHEQUE DROP COLUMN NUM_CHEQUE;
ALTER TABLE CHEQUE ADD COLUMN NUM_CHEQUE VARCHAR(20);

ALTER TABLE CHEQUE DROP COLUMN NUM_AGENCIA;
ALTER TABLE CHEQUE ADD COLUMN NUM_AGENCIA VARCHAR(20);
-- AMADEU 10/09/2005

-- AMADEU 13/09/2005
ALTER TABLE ANDAMENTO ALTER COLUMN DES_ANDAMENTO DROP NOT NULL;
-- AMADEU 13/09/2005

-- AMADEU 21/09/2005
ALTER TABLE PROCESSO ADD STR_OBSERVACAO TEXT;
--	AMADEU 21/09/2005

-- AMADEU 22/09/2005 (AS TAXAS AGORA SÃO REFERENTES AO PROCESSO) 
ALTER TABLE TAXA DROP COLUMN ACORDO_CODIGO CASCADE;
ALTER TABLE TAXA ADD COLUMN PROCESSO_CODIGO INT4;
ALTER TABLE TAXA ADD CONSTRAINT taxa_proc_codigo_fkey 
	FOREIGN KEY (PROCESSO_CODIGO) 
	REFERENCES PROCESSO(PROCESSO_CODIGO) 
	ON UPDATE NO ACTION ON DELETE NO ACTION;
-- AMADEU 22/09/2005

/*-- FERNANDO 09/10/2005
CREATE SEQUENCE SEQ_INDICE_REAJUSTE;
CREATE TABLE INDICE_REAJUSTE (
  INDICE_REAJUSTE_CODIGO INTEGER NOT NULL,
  DES_INDICE_REAJUSTE VARCHAR(50) NULL,
  STR_NOME VARCHAR(10) NOT NULL,
  PRIMARY KEY(INDICE_REAJUSTE_CODIGO)
);

CREATE SEQUENCE SEQ_PERIODO_INDICE;
CREATE TABLE PERIODO_INDICE (
  PERIODO_INDICE_CODIGO INTEGER NOT NULL,
  INDICE_REAJUSTE_CODIGO INTEGER NOT NULL,
  MES INTEGER NULL,
  ANO INTEGER NULL,
  VALOR FLOAT NULL,
  PRIMARY KEY(PERIODO_INDICE_CODIGO),
  FOREIGN KEY(INDICE_REAJUSTE_CODIGO)
    REFERENCES INDICE_REAJUSTE(INDICE_REAJUSTE_CODIGO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

-- FERNANDO 09/10/2005
*/
-- AMADEU 10/10/2005
ALTER TABLE ACORDO ADD VL_INDICE_MULTA FLOAT;
ALTER TABLE ACORDO ADD VL_JUROS_MES FLOAT;
ALTER TABLE ACORDO ADD VL_INDICE_CLASULA_PENAL_MES FLOAT;
ALTER TABLE ACORDO ADD INDICE_REAJUSTE_CODIGO INTEGER;
ALTER TABLE ACORDO ADD CONSTRAINT INDICE_REAJUSTE_CODIGO_FKEY FOREIGN KEY(INDICE_REAJUSTE_CODIGO)
    REFERENCES INDICE_REAJUSTE(INDICE_REAJUSTE_CODIGO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION;
ALTER TABLE parcela_acordo ADD VL_CLAUSULA_PENAL FLOAT;
ALTER TABLE PAGAMENTO ADD VL_CORRECAO FLOAT;      
-- AMADEU 10/10/2005

-- AMADEU 04/11/2005
CREATE SEQUENCE SEQ_DIRETORIO;
CREATE TABLE DIRETORIO (
  DIRETORIO_CODIGO INTEGER NOT NULL,
  NOM_DIRETORIO VARCHAR(255) NULL,
  DIRETORIO_PAI_CODIGO INTEGER NULL,
  STR_SORT_KEY VARCHAR(4000) NOT NULL, --CHAVE DE ORDENAÇÃO HIERÁRQUICA DOS DIRETORIOS (00/01/02)
  PRIMARY KEY(DIRETORIO_CODIGO),
  FOREIGN KEY(DIRETORIO_PAI_CODIGO)
    REFERENCES DIRETORIO(DIRETORIO_CODIGO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE SEQUENCE SEQ_DOCUMENTO;
CREATE TABLE DOCUMENTO (
  DOCUMENTO_CODIGO INTEGER NOT NULL,
  DIRETORIO_CODIGO INTEGER NOT NULL,
  NOM_DOCUMENTO VARCHAR(1000) NOT NULL,
  BLB_DOCUMENTO BYTEA NOT NULL,
  PRIMARY KEY(DOCUMENTO_CODIGO),
  FOREIGN KEY(DIRETORIO_CODIGO)
    REFERENCES DIRETORIO(DIRETORIO_CODIGO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);
-- AMADEU 04/11/2005

-- AMADEU 17/11/2005
CREATE SEQUENCE SEQ_JURISPRUDENCIA;
CREATE TABLE JURISPRUDENCIA (
	JURISPRUDENCIA_CODIGO INTEGER NOT NULL,
	STR_TITULO VARCHAR(3000) NOT NULL,
	DOCUMENTO_CODIGO INTEGER NOT NULL,
	AREA_ATUACAO_CODIGO INTEGER NOT NULL,
	PRIMARY KEY(JURISPRUDENCIA_CODIGO),
	FOREIGN KEY(DOCUMENTO_CODIGO)
    REFERENCES DOCUMENTO(DOCUMENTO_CODIGO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
); 

CREATE SEQUENCE SEQ_LINK;
CREATE TABLE LINK (
	LINK_CODIGO INTEGER NOT NULL,
	NOM_LINK VARCHAR(100) NOT NULL,
	STR_ENDERECO VARCHAR(400)NOT NULL,
	PRIMARY KEY(LINK_CODIGO)
);

ALTER TABLE processo ALTER COLUMN dt_distribuicao drop not NULL;

-- AMADEU 17/11/2005

-- !!!!!! NOVA VERSÃO A PARTIR DAQUI !!!!!! ---

-- AMADEU 11/12/2005
ALTER TABLE pessoa ADD STR_EMAIL VARCHAR(200);
ALTER TABLE cheque ADD DT_RECEBIMENTO DATE;
ALTER TABLE cheque ADD DT_COMPENSACAO DATE;
-- AMADEU 11/12/2005

-- !!!!!! NOVA VERSÃO A PARTIR DAQUI !!!!!! ---

-- AMADEU 30/12/2005
ALTER TABLE processo
	ADD CONSTRAINT "processo_num_unique"
	UNIQUE ("str_numero_processo");
-- AMADEU 30/12/2005	

--AMADEU 07/01/2006
CREATE SEQUENCE SEQ_PARCEIRO;
CREATE TABLE PARCEIRO
(
  PESSOA_CODIGO int4 NOT NULL,
  DES_SERVICO TEXT,
  CONSTRAINT "PARCEIRO_PK" PRIMARY KEY (PESSOA_CODIGO),
  CONSTRAINT "PESSOA_PARCEIRO" FOREIGN KEY (PESSOA_CODIGO) 
  	REFERENCES pessoa (pessoa_codigo) 
  	ON DELETE NO ACTION
  	ON UPDATE NO ACTION
); 

ALTER TABLE documento DROP COLUMN blb_documento;
ALTER TABLE documento ADD COLUMN blb_documento TEXT;

--AMADEU 05/07/2006

ALTER TABLE PARTE
ADD CONSTRAINT "PARTE_PRIMARY_KEY"
PRIMARY KEY(PROCESSO_CODIGO,PESSOA_CODIGO);

ALTER TABLE andamento DROP COLUMN des_andamento;
ALTER TABLE andamento ADD COLUMN des_andamento varchar(1000);

-- AMADEU 28/01/2007
ALTER TABLE PROCESSO ADD COLUMN APTO INTEGER NULL;
ALTER TABLE PROCESSO ADD COLUMN BLOCO VARCHAR(5) NULL;
-- AMADEU 28/01/2007
	