SELECT  PROCESSO.PROCESSO_CODIGO,OJ.ORGAO_JUDICIARIO_CODIGO, 
        OJ.DES_ORGAO_JUDICIARIO , OJ.JUIZO_CODIGO, J.DES_JUIZO, 
        CP.CLASSE_PROCESSO_CODIGO, CP.DES_CLASSE_PROCESSO, 
        STR_NUMERO_PROCESSO,PESSOA.NOME AS NOME_RESPOSNSAVEL,
        ANDAMENTO.DES_ANDAMENTO,ANDAMENTO.DTH_PRAZO, 
        TIPO_ANDAMENTO.DES_TIPO_ANDAMENTO
FROM PROCESSO,ORGAO_JUDICIARIO OJ,
     CLASSE_PROCESSO CP,JUIZO J,PESSOA,PARTE,
     ANDAMENTO,TIPO_ANDAMENTO
WHERE 
    PROCESSO.ORGAO_JUDICIARIO_CODIGO = OJ.ORGAO_JUDICIARIO_CODIGO 
    AND OJ.JUIZO_CODIGO = J.JUIZO_CODIGO 
    AND PROCESSO.CLASSE_PROCESSO_CODIGO = CP.CLASSE_PROCESSO_CODIGO 
    AND STS_PROCESSO = 1 
    AND PROCESSO.PROCESSO_CODIGO = PARTE.PROCESSO_CODIGO
    AND PARTE.PESSOA_CODIGO = PESSOA.PESSOA_CODIGO
    AND PESSOA.PESSOA_CODIGO IN
            (SELECT PARTE.PESSOA_CODIGO 
             FROM PARTE
                 INNER JOIN PESSOA ON (PARTE.PESSOA_CODIGO = PESSOA.PESSOA_CODIGO)
             WHERE PARTE.PROCESSO_CODIGO = PROCESSO.PROCESSO_CODIGO
                  AND TIPO_PARTE = 2
                  AND PESSOA.PESSOA_CODIGO = 1 --5  
            )
    AND ANDAMENTO.ANDAMENTO_CODIGO IN
            (SELECT ANDAMENTO_CODIGO FROM ANDAMENTO
             WHERE ANDAMENTO.PROCESSO_CODIGO = PROCESSO.PROCESSO_CODIGO
               AND TIPO_ANDAMENTO_CODIGO = 1
               AND (1 IS NULL OR DTH_PRAZO >= DATE '09/09/2005')
               AND (2 IS NULL OR DTH_PRAZO <= DATE '12/09/2005')     
            )
    AND TIPO_ANDAMENTO.TIPO_ANDAMENTO_CODIGO = ANDAMENTO.TIPO_ANDAMENTO_CODIGO        
   